create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  category text not null default 'General',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  sale_number text not null unique,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0,
  event_id text not null default 'default',
  payment_method text not null check (payment_method in ('cash', 'card', 'transfer')),
  status text not null default 'pending' check (status in ('pending', 'completed', 'synced')),
  created_at timestamptz not null default now(),
  synced_at timestamptz
);

create table if not exists public.events (
  id text primary key,
  name text not null unique,
  location text not null default '',
  is_active boolean not null default true,
  start_date date,
  end_date date,
  constraint events_date_range_valid check (
    start_date is null or end_date is null or start_date <= end_date
  ),
  created_at timestamptz not null default now()
);

alter table public.events
  add column if not exists location text not null default '';

alter table public.events
  add column if not exists is_active boolean not null default true;

alter table public.events
  add column if not exists start_date date,
  add column if not exists end_date date;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'events_date_range_valid'
      and conrelid = 'public.events'::regclass
  ) then
    alter table public.events
      add constraint events_date_range_valid
      check (start_date is null or end_date is null or start_date <= end_date);
  end if;
end
$$;

create table if not exists public.event_expenses (
  id uuid primary key default gen_random_uuid(),
  event_id text not null references public.events (id) on delete cascade,
  category text not null,
  description text not null,
  amount numeric(12,2) not null check (amount > 0),
  created_at timestamptz not null default now()
);

create index if not exists idx_event_expenses_event_created
  on public.event_expenses (event_id, created_at desc);

grant select, insert, update, delete on public.events to anon, authenticated;
grant select, insert, update, delete on public.event_expenses to anon, authenticated;

alter table public.events enable row level security;
alter table public.event_expenses enable row level security;

drop policy if exists "Public can manage events" on public.events;
create policy "Public can manage events" on public.events
  for all to anon, authenticated
  using (true)
  with check (true);

drop policy if exists "Public can manage event expenses" on public.event_expenses;
create policy "Public can manage event expenses" on public.event_expenses
  for all to anon, authenticated
  using (true)
  with check (true);

alter table public.sales
  add column if not exists event_id text not null default 'default';

alter table public.sales
  add column if not exists items jsonb not null default '[]'::jsonb;

create index if not exists idx_products_category on public.products (category);
create index if not exists idx_products_name on public.products (name);
create index if not exists idx_sales_status on public.sales (status);
create index if not exists idx_sales_created_at on public.sales (created_at desc);

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_updated_at_products on public.products;
create trigger set_updated_at_products
before update on public.products
for each row
execute function public.update_updated_at_column();
