create table if not exists public.products (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  price numeric(12,2) not null default 0,
  stock integer not null default 0,
  category text not null default 'General',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sales (
  id bigint generated by default as identity primary key,
  sale_number text not null unique,
  items jsonb not null default '[]'::jsonb,
  total numeric(12,2) not null default 0,
  payment_method text not null check (payment_method in ('cash', 'card', 'transfer')),
  status text not null default 'pending' check (status in ('pending', 'completed', 'synced')),
  created_at timestamptz not null default now(),
  synced_at timestamptz
);

create index if not exists idx_products_category on public.products (category);
create index if not exists idx_products_name on public.products (name);
create index if not exists idx_sales_status on public.sales (status);
create index if not exists idx_sales_created_at on public.sales (created_at desc);

create or replace function public.update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists set_updated_at_products on public.products;
create trigger set_updated_at_products
before update on public.products
for each row
execute function public.update_updated_at_column();
